name: Spam Detection

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  detect-spam:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn==1.5.1  # Use the version matching your model
          pip install joblib  # Use joblib to load the model if it was saved with it
          pip install requests  # Required to use GitHub API for hiding comments

      - name: Run Spam Detection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/spam_detector.py "${{ github.event.comment.body }}" "${{ github.event.comment.id }}" "${{ github.event.comment.url }}"
